name: Publish Site

on:
  push:
    branches:
      - source

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.0.0
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@bfd5d2fa3abefe9ac3837c6aa9b685122d42feda
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
          branch: master
          hugoVersion: extended_0.66.0
