name: Publish Site

on:
  push:
    branches:
      - source

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@v1.1
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
          branch: master
          hugoVersion: extended_0.66.0
